name: Daily Flash-Attention Build

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间午夜运行
  workflow_dispatch:  # 允许手动触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.6.0-devel-ubuntu22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Create virtual environment
      run: uv venv -p 3.12 --seed

    - name: Install PyTorch nightly
      run: |
        source .venv/bin/activate
        pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu126

    - name: Build flash-attention wheel
      run: |
        source .venv/bin/activate
        mkdir -p wheelhouse
        MAX_JOBS=4 FLASH_ATTENTION_FORCE_BUILD=TRUE \
        python -m pip wheel --no-build-isolation --no-deps flash-attn -w ./wheelhouse

    - name: Get package versions
      id: versions
      run: |
        source .venv/bin/activate
        echo "TORCH_VERSION=$(python -c "import torch; print(torch.__version__)")" >> $GITHUB_OUTPUT
        echo "FLASH_ATTENTION_VERSION=$(python -c "import importlib.metadata; print(importlib.metadata.version('flash-attn'))")" >> $GITHUB_OUTPUT
        echo "CUDA_VERSION=cu126" >> $GITHUB_OUTPUT

    - name: Create tag name
      id: tag
      run: |
        TAG_NAME="${{ steps.versions.outputs.TORCH_VERSION }}+${{ steps.versions.outputs.FLASH_ATTENTION_VERSION }}+${{ steps.versions.outputs.CUDA_VERSION }}"
        echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.TAG_NAME }}
        files: wheelhouse/*.whl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}